apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bumwg0j4i-python-gitops
  description: This is GitOps manifest for bumwg0j4i-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: bumwg0j4i-python
    janus-idp.io/tekton: bumwg0j4i-python 
    backstage.io/kubernetes-id: bumwg0j4i-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bumwg0j4i-python
