apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bumwg0j4i-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:9d49b88b23a1267d61c38fc75a4f1a6ad867593c@sha256:9ab043f04067d64cd73361bad976df76431579eb6557dd7031d0831c3cd7821f
          name: container-image
